version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: npm
    directory: /marketing-site
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: npm
    directory: /wml-server
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: cargo
    directory: /engine-wasm/engine
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust

  - package-ecosystem: cargo
    directory: /transport-rust
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust

  - package-ecosystem: cargo
    directory: /browser/src-tauri
    schedule:
      interval: weekly
    labels:
      - dependencies
      - rust
