packages:
  # Active Node package today
  - "engine-wasm/host-sample"
  - "browser/frontend"

catalog:
  "@types/node": "^25.3.3"
  "@typescript-eslint/eslint-plugin": "^8.56.1"
  "@typescript-eslint/parser": "^8.57.0"
  eslint: "^10.0.2"
  eslint-config-prettier: "^10.1.8"
  globals: "^17.4.0"
  lit: "^3.3.2"
  prettier: "^3.8.1"
  typescript: "^5.9.3"
  vite: "^7.3.1"
