packages:
  # Active Node package today
  - "engine-wasm/host-sample"
  - "browser/frontend"

catalog:
  "@types/node": "^25.6.0"
  "@typescript-eslint/eslint-plugin": "^8.58.0"
  "@typescript-eslint/parser": "^8.58.0"
  eslint: "^10.2.1"
  eslint-config-prettier: "^10.1.8"
  globals: "^17.4.0"
  lit: "^3.3.2"
  prettier: "^3.8.2"
  typescript: "^6.0.2"
  vite: "^8.0.5"
