import { WAVES_CONFIG } from './waves-config';

const locale = {
  app: {
    brand: 'Waves',
    tagline: WAVES_CONFIG.appTagline,
    description: WAVES_CONFIG.appDescription
  },
  shell: {
    back: 'Back',
    reload: 'Reload',
    go: 'Go',
    address: 'Address',
    addressPlaceholder: 'Enter a WAP or WML URL',
    historyControls: 'History controls',
    deckView: 'Deck View',
    deckViewport: 'Deck viewport',
    simulatorStage: 'WAP simulator stage',
    referenceView: 'Reference View',
    idle: 'idle',
    up: 'Up',
    select: 'Select',
    down: 'Down',
    viewportCols: 'Viewport Cols',
    displayScale: 'Display Scale',
    utilityRail: 'Close Developer Tools',
    inspector: 'Developer Tools',
    applicationStatus: 'Application status',
    document: 'Document',
    source: 'Source',
    diagnostics: 'Diagnostics',
    status: 'Status',
    developerTools: 'Developer Tools',
    developerToolsActions: 'Developer tools actions',
    developerToolsPanels: 'Developer tools panels',
    openInWindow: 'Open in Window',
    overview: 'Overview',
    transport: 'Transport',
    runtime: 'Runtime',
    timeline: 'Timeline',
    navigation: 'Navigation',
    activeCard: 'Active Card',
    focusedLink: 'Focused Link',
    nextTimer: 'Next Timer',
    events: 'Events',
    elapsed: 'Elapsed',
    contentType: 'Content Type',
    finalAddress: 'Final Address',
    noActiveDeck: 'No active deck',
    noCoverage: 'No fixture coverage',
    currentSessionSummary: 'Current session summary',
    transportSummary: 'Transport summary',
    runtimeSummary: 'Runtime summary',
    timelineDescription: 'Ordered host and engine events for the current session.',
    sourceDescription: 'Load a raw WML deck into the current browser session.',
    health: 'Health',
    render: 'Render',
    snapshot: 'Snapshot',
    clearExternalIntent: 'Clear External Intent',
    exportTimeline: 'Export Timeline',
    clearTimeline: 'Clear Timeline',
    rawWmlPaste: 'Raw WML Paste',
    baseUrl: 'Base URL',
    loadRawWml: 'Load Raw WML',
    sessionState: 'Session State',
    transportResponse: 'Transport Response',
    runtimeSnapshot: 'Runtime Snapshot',
    eventTimeline: 'Event Timeline',
    firstRenderPending: 'Waiting for first deck render...',
    navigationPending: 'Loading next page...',
    mode: 'Mode',
    localMode: 'Examples',
    networkMode: 'Network',
    localExample: 'Local Example',
    loadLocal: 'Load',
    route: 'Route',
    profile: 'Profile',
    classCReferenceProfile: 'Class C Reference',
    routeLocalFixtures: 'Local fixtures',
    routeNetwork: (host: string) => `Network — ${host}`,
    localExampleNotes: 'Local Example Notes',
    localExampleCoverage: 'Coverage:',
    localExampleDescription: 'Description:',
    localExampleGoal: 'Goal:',
    localExampleTestingAc: 'Testing AC',
    welcomeHelpTitle: 'Browse a WAP deck',
    welcome: 'Welcome',
    showWelcomeOnLaunch: 'Show this welcome screen on launch',
    welcomeIntro:
      'Waves emulates a WAP 1.2.1 / WML 1.3 handset — decks and cards, not modern web pages.',
    welcomeModes:
      'Local mode browses bundled example decks with no network required. Network mode fetches real WML through a WAP gateway.',
    takeTheTour: 'Take the Tour',
    tryLocalExamples: 'Try Local Examples',
    connectToServer: 'Connect to a WAP Server',
    controlsReferenceTitle: 'Controls',
    controlsReferenceBody:
      'Up and Down move focus between links. Select activates the focused link. Back returns through card history.',
    applicationShortcutsTitle: 'Application shortcuts',
    commandUnavailable: 'Unavailable',
    troubleshootingTitle: 'Troubleshooting',
    troubleshootingBody:
      'No network available? Switch Mode to Local to keep browsing bundled examples without a WAP gateway.'
  },
  sampleDeck: {
    intro: WAVES_CONFIG.appTagline,
    next: 'Go to next card',
    external: 'External link',
    nextCard: 'You are on the next card.',
    home: 'Go home'
  },
  inspector: {
    tab: 'Inspector',
    title: 'Engine Inspector',
    description: 'Bounded, local, read-only engine events and snapshots.',
    start: 'Start Inspector',
    stop: 'Stop',
    hostPolicy: 'Host policy',
    disabledByDefault: 'Disabled by default',
    session: 'Session',
    off: 'Off',
    defaultDisabledDetail:
      'Read-only and disabled by default. Starting requires the local host policy at launch.',
    captureControls: 'Inspector capture controls',
    eventGroup: 'Event group',
    filter: 'Filter retained events',
    filterPlaceholder: 'Sequence, kind, card, or value',
    refreshSnapshot: 'Refresh Snapshot',
    exportCapture: 'Export Capture',
    inspectorOff: 'Inspector off.',
    accounting: 'Inspector capacity and gap accounting',
    matching: 'matching',
    producerGaps: 'producer gaps',
    frontendDrops: 'frontend drops',
    eventStream: 'Event stream',
    eventDescription:
      'Ordered only by the engine sequence cursor; newest bounded rows remain visible.',
    noEvents: 'No retained events.',
    noMatchingEvents: 'No retained events match the current filter.',
    engineDebugEvents: 'Engine debug events',
    boundedSnapshot: 'Bounded snapshot',
    noSnapshot: 'No snapshot captured'
  },
  statusPrefix: {
    error: 'Error:',
    fetchFailed: 'Fetch failed:',
    deckParseFailed: 'Deck parse failed:',
    scriptExecutionFailed: 'Script error (',
    loading: 'Loading ',
    followingExternalIntent: 'Following external intent:',
    checkingGateway: 'Checking WAP gateway',
    ready: 'Ready',
    fetchedAndLoaded: 'Fetched and loaded'
  },
  errors: {
    urlRequired: 'URL is required',
    unknownTransportFailure: 'unknown transport failure',
    missingWmlPayload: 'Fetch succeeded but returned no WML payload.',
    viewportColsRange: (minCols: number, maxCols: number) =>
      `viewport cols must be an integer from ${minCols} through ${maxCols}`,
    timelineRequiresEvent: 'Timeline export requires at least one event.',
    timelineRequiresChronology: 'Timeline export must contain both action and state chronology.'
  },
  status: {
    starting: `Starting ${WAVES_CONFIG.appTagline}...`,
    ready: 'Ready.',
    readyNetwork: (url: string) => `Ready. WAP gateway responded at ${url}.`,
    bootShellReady: 'Shell ready.',
    bootEngineReady: 'Engine ready.',
    bootDeckReady: 'Deck ready.',
    localModeEnabled: 'Local mode enabled. Network fetches are disabled.',
    networkModeEnabled: (url: string) =>
      url ? `Checking WAP gateway at ${url}...` : 'Network mode ready. Enter or choose an address.',
    loadedLocalDeck: (label: string) => `Loaded local example: ${label}`,
    localExternalIntentCaptured: (url: string) =>
      `Local mode captured external intent: ${url} (not fetched).`,
    health: (message: string) => `Health: ${message}`,
    rawWmlLoaded: 'Raw WML loaded and rendered (debug mode).',
    renderedCurrentCard: 'Rendered current card.',
    navigateBackEngine: 'navigateBack invoked (engine history).',
    navigateBackBrowser: 'navigateBack invoked (browser history).',
    navigateBackNone: 'No back history available.',
    snapshotRefreshed: 'Snapshot refreshed.',
    clearedExternalIntent: 'Cleared external navigation intent.',
    noTimelineToExport: 'No timeline events to export yet.',
    exportedTimeline: 'Exported timeline JSON.',
    clearedTimeline: 'Cleared event timeline.',
    developerToolsOpened: 'Developer tools opened.',
    developerToolsHidden: 'Developer tools hidden.',
    developerToolsWindowFailed: (message: string) =>
      `Developer tools window could not open. ${message}`,
    developerToolsInspectorStateFailed: 'Inspector state could not be sent to the detached window.',
    keyboard: (key: string) => `Keyboard: ${key}`,
    keyboardBackEngine: 'Keyboard: back (engine history)',
    keyboardBackBrowser: 'Keyboard: back (browser history)',
    keyboardBackNone: 'Keyboard: no back history',
    handledKey: (key: string) => `Handled key: ${key}`,
    loading: (url: string) => `Loading ${url}...`,
    followingExternalIntent: (url: string) => `Following external intent: ${url}`,
    loadingPreviousPage: (url: string) => `Loading previous page: ${url}`,
    fetchFailed: (message: string) => `Fetch failed: ${message}`,
    // Distinct from fetchFailed: the transport request itself succeeded, but the
    // payload it returned could not be parsed/used as a WML deck. Kept as
    // separate wording so users (and anyone debugging a deck) don't confuse a
    // malformed-content failure with a network-layer one (see U2).
    deckParseFailed: (message: string) => `Deck parse failed: ${message}`,
    // Distinct wording for a WMLScript fatal trap, using the engine's own
    // error-category taxonomy so it reads differently from both a network
    // failure and a deck-parse failure (see U2).
    scriptExecutionFailed: (categoryLabel: string, message: string) =>
      `Script error (${categoryLabel}): ${message}`,
    fetchedAndLoadedDeck: (url: string) => `Fetched and loaded deck from ${url}`,
    networkUnavailableToast:
      'Could not reach the WAP server or gateway. Check that Kannel is running and the address is reachable.',
    networkUnavailable:
      'Could not reach the WAP server or gateway. Network mode remains available.',
    gatewayCheckFailed: (url: string, reason: string) =>
      `Error: WAP gateway not verified at ${url}. ${reason}`,
    error: (message: string) => `Error: ${message}`,
    scriptDialogAlert: (message: string) => `Script alert("${message}") shown.`,
    scriptDialogConfirm: (message: string) =>
      `Script confirm("${message}") - Waves answered: Cancel (deterministic default).`,
    scriptDialogPrompt: (message: string, value: string) =>
      `Script prompt("${message}") - Waves answered: "${value}" (deterministic default).`
  }
} as const;

export const WAVES_COPY = locale;
