use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use crate::{
    DrawCmd, EngineTraceEntry, RenderList, ScriptCallArgLiteral, ScriptDialogRequestLiteral,
    ScriptErrorCategoryLiteral, ScriptErrorClassLiteral, ScriptExecutionOutcome,
    ScriptInvocationOutcome, ScriptNavigationCacheControlPolicyLiteral,
    ScriptNavigationIntentLiteral, ScriptNavigationPostContextLiteral,
    ScriptNavigationRequestPolicyLiteral, ScriptTimerRequestLiteral, ScriptValueLiteral,
    WmlLoadDiagnostic, WmlLoadDiagnosticClassLiteral, WmlLoadDiagnosticCodeLiteral,
    WmlLoadDiagnosticOutcomeLiteral,
};

const GENERATED_HEADER: &str = concat!(
    "// AUTO-GENERATED FILE. DO NOT EDIT.\n",
    "// Schema: wavenav-runtime-dto/v1\n",
    "// Sources: engine-wasm/engine/src/{engine_script_types.rs,engine_wml_types.rs,render/render_list.rs}\n",
    "// Generated by: pnpm --dir engine-wasm/host-sample run contracts:generate\n\n",
);

fn push_decl<T: TS>(output: &mut String) {
    output.push_str("export ");
    output.push_str(&T::decl(&Config::default()));
    output.push_str("\n\n");
}

pub fn render_runtime_contract() -> String {
    let mut output = String::from(GENERATED_HEADER);
    push_decl::<WmlLoadDiagnosticClassLiteral>(&mut output);
    push_decl::<WmlLoadDiagnosticCodeLiteral>(&mut output);
    push_decl::<WmlLoadDiagnosticOutcomeLiteral>(&mut output);
    push_decl::<WmlLoadDiagnostic>(&mut output);
    push_decl::<ScriptErrorClassLiteral>(&mut output);
    push_decl::<ScriptErrorCategoryLiteral>(&mut output);
    push_decl::<ScriptNavigationIntentLiteral>(&mut output);
    push_decl::<ScriptNavigationCacheControlPolicyLiteral>(&mut output);
    push_decl::<ScriptNavigationPostContextLiteral>(&mut output);
    push_decl::<ScriptNavigationRequestPolicyLiteral>(&mut output);
    push_decl::<ScriptValueLiteral>(&mut output);
    push_decl::<ScriptCallArgLiteral>(&mut output);
    push_decl::<ScriptExecutionOutcome>(&mut output);
    push_decl::<ScriptInvocationOutcome>(&mut output);
    push_decl::<ScriptDialogRequestLiteral>(&mut output);
    push_decl::<ScriptTimerRequestLiteral>(&mut output);
    push_decl::<EngineTraceEntry>(&mut output);
    push_decl::<DrawCmd>(&mut output);
    push_decl::<RenderList>(&mut output);
    output.truncate(output.trim_end().len());
    output.push('\n');
    output
}

pub fn runtime_contract_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../contracts/generated/runtime-dtos.ts")
}

pub fn write_runtime_contract(path: &Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, render_runtime_contract())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_has_provenance_and_all_boundary_types() {
        let output = render_runtime_contract();

        assert!(output.starts_with(GENERATED_HEADER));
        for type_name in [
            "WmlLoadDiagnostic",
            "ScriptExecutionOutcome",
            "ScriptInvocationOutcome",
            "ScriptDialogRequest",
            "ScriptTimerRequest",
            "EngineTraceEntry",
            "DrawCmd",
            "RenderList",
        ] {
            assert!(
                output.contains(&format!("export type {type_name} =")),
                "missing generated declaration for {type_name}"
            );
        }
        assert!(output.contains("navigationIntent: ScriptNavigationIntent"));
        assert!(output.contains("requiresRefresh: boolean"));
        assert!(!output.contains("effects:"));
    }

    #[test]
    fn generated_contract_write_is_deterministic() {
        let path = std::env::temp_dir().join(format!(
            "wavenav-runtime-dtos-{}-{}.ts",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));

        write_runtime_contract(&path).expect("first generation should succeed");
        let first = fs::read(&path).expect("first output should be readable");
        write_runtime_contract(&path).expect("second generation should succeed");
        let second = fs::read(&path).expect("second output should be readable");

        assert_eq!(first, second);
        let _ = fs::remove_file(path);
    }
}
