use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use crate::{
    engine_debug_typescript_contract, engine_viewport_typescript_contract, DrawCmd,
    EngineAffordance, EngineAffordanceSource, EngineCardDisplayMetadata, EngineControlAssociation,
    EngineDebugBufferSnapshot, EngineDebugCapabilities, EngineDebugCloseSessionOutcome,
    EngineDebugCloseSessionRequest, EngineDebugCloseSessionResult, EngineDebugCollectionSummary,
    EngineDebugError, EngineDebugErrorCode, EngineDebugEvent, EngineDebugEventBatch,
    EngineDebugEventKind, EngineDebugEventPayload, EngineDebugExternalNavigationSnapshot,
    EngineDebugMaskingPolicy, EngineDebugNamedValue, EngineDebugOpenSessionOutcome,
    EngineDebugOpenSessionRequest, EngineDebugPollEventsOutcome, EngineDebugPollEventsRequest,
    EngineDebugPostfieldResolution, EngineDebugPostfieldResolutionSource,
    EngineDebugRedactionReason, EngineDebugSession, EngineDebugSnapshot,
    EngineDebugSnapshotOutcome, EngineDebugSnapshotRequest, EngineDebugTimerSnapshot,
    EngineDebugTimestampKind, EngineDebugValue, EngineDeckDisplayMetadata, EngineFocusState,
    EngineFocusTargetKind, EngineFrameRow, EngineFrameSegment, EngineInputEvent, EngineInputKey,
    EnginePresentationFrame, EngineSelectionState, EngineTraceEntry, EngineViewport,
    EngineViewportError, RenderList, ScriptCallArgLiteral, ScriptDialogRequestLiteral,
    ScriptErrorCategoryLiteral, ScriptErrorClassLiteral, ScriptExecutionOutcome,
    ScriptInvocationOutcome, ScriptNavigationCacheControlPolicyLiteral,
    ScriptNavigationIntentLiteral, ScriptNavigationMethodLiteral,
    ScriptNavigationPostContextLiteral, ScriptNavigationPostFieldLiteral,
    ScriptNavigationRequestIntentLiteral, ScriptNavigationRequestPolicyLiteral,
    ScriptTimerRequestLiteral, ScriptValueLiteral, WmlLoadDiagnostic,
    WmlLoadDiagnosticClassLiteral, WmlLoadDiagnosticCodeLiteral, WmlLoadDiagnosticOutcomeLiteral,
};

const GENERATED_HEADER: &str = concat!(
    "// AUTO-GENERATED FILE. DO NOT EDIT.\n",
    "// Schema: wavenav-runtime-dto/v1\n",
    "// Sources: engine-wasm/engine/src/{engine_debug_contract.rs,engine_script_types.rs,engine_wml_types.rs,render/frame.rs,render/render_list.rs}\n",
    "// Generated by: pnpm --dir engine-wasm/host-sample run contracts:generate\n\n",
);

fn push_decl<T: TS>(output: &mut String) {
    output.push_str("export ");
    output.push_str(&T::decl(&Config::default()));
    output.push_str("\n\n");
}

pub fn render_runtime_contract() -> String {
    let mut output = String::from(GENERATED_HEADER);
    push_decl::<WmlLoadDiagnosticClassLiteral>(&mut output);
    push_decl::<WmlLoadDiagnosticCodeLiteral>(&mut output);
    push_decl::<WmlLoadDiagnosticOutcomeLiteral>(&mut output);
    push_decl::<WmlLoadDiagnostic>(&mut output);
    push_decl::<ScriptErrorClassLiteral>(&mut output);
    push_decl::<ScriptErrorCategoryLiteral>(&mut output);
    push_decl::<ScriptNavigationIntentLiteral>(&mut output);
    push_decl::<ScriptNavigationCacheControlPolicyLiteral>(&mut output);
    push_decl::<ScriptNavigationMethodLiteral>(&mut output);
    push_decl::<ScriptNavigationPostFieldLiteral>(&mut output);
    push_decl::<ScriptNavigationRequestIntentLiteral>(&mut output);
    push_decl::<ScriptNavigationPostContextLiteral>(&mut output);
    push_decl::<ScriptNavigationRequestPolicyLiteral>(&mut output);
    push_decl::<ScriptValueLiteral>(&mut output);
    push_decl::<ScriptCallArgLiteral>(&mut output);
    push_decl::<ScriptExecutionOutcome>(&mut output);
    push_decl::<ScriptInvocationOutcome>(&mut output);
    push_decl::<ScriptDialogRequestLiteral>(&mut output);
    push_decl::<ScriptTimerRequestLiteral>(&mut output);
    push_decl::<EngineTraceEntry>(&mut output);
    push_decl::<EngineDebugMaskingPolicy>(&mut output);
    push_decl::<EngineDebugTimestampKind>(&mut output);
    push_decl::<EngineDebugRedactionReason>(&mut output);
    push_decl::<EngineDebugValue>(&mut output);
    push_decl::<EngineDebugNamedValue>(&mut output);
    push_decl::<EngineDebugPostfieldResolutionSource>(&mut output);
    push_decl::<EngineDebugPostfieldResolution>(&mut output);
    push_decl::<EngineDebugEventKind>(&mut output);
    push_decl::<EngineDebugEventPayload>(&mut output);
    push_decl::<EngineDebugEvent>(&mut output);
    push_decl::<EngineDebugBufferSnapshot>(&mut output);
    push_decl::<EngineDebugCollectionSummary>(&mut output);
    push_decl::<EngineDebugTimerSnapshot>(&mut output);
    push_decl::<EngineDebugExternalNavigationSnapshot>(&mut output);
    push_decl::<EngineDebugSnapshot>(&mut output);
    push_decl::<EngineDebugCapabilities>(&mut output);
    push_decl::<EngineDebugOpenSessionRequest>(&mut output);
    push_decl::<EngineDebugSession>(&mut output);
    push_decl::<EngineDebugPollEventsRequest>(&mut output);
    push_decl::<EngineDebugEventBatch>(&mut output);
    push_decl::<EngineDebugSnapshotRequest>(&mut output);
    push_decl::<EngineDebugCloseSessionRequest>(&mut output);
    push_decl::<EngineDebugCloseSessionResult>(&mut output);
    push_decl::<EngineDebugErrorCode>(&mut output);
    push_decl::<EngineDebugError>(&mut output);
    push_decl::<EngineDebugOpenSessionOutcome>(&mut output);
    push_decl::<EngineDebugPollEventsOutcome>(&mut output);
    push_decl::<EngineDebugSnapshotOutcome>(&mut output);
    push_decl::<EngineDebugCloseSessionOutcome>(&mut output);
    output.push_str(&engine_debug_typescript_contract());
    output.push('\n');
    push_decl::<EngineViewport>(&mut output);
    push_decl::<EngineViewportError>(&mut output);
    output.push_str(&engine_viewport_typescript_contract());
    output.push('\n');
    push_decl::<EngineDeckDisplayMetadata>(&mut output);
    push_decl::<EngineCardDisplayMetadata>(&mut output);
    push_decl::<EngineFrameRow>(&mut output);
    push_decl::<EngineFocusTargetKind>(&mut output);
    push_decl::<EngineFrameSegment>(&mut output);
    push_decl::<EngineFocusState>(&mut output);
    push_decl::<EngineSelectionState>(&mut output);
    push_decl::<EngineAffordanceSource>(&mut output);
    push_decl::<EngineControlAssociation>(&mut output);
    push_decl::<EngineAffordance>(&mut output);
    push_decl::<EnginePresentationFrame>(&mut output);
    push_decl::<EngineInputKey>(&mut output);
    push_decl::<EngineInputEvent>(&mut output);
    push_decl::<DrawCmd>(&mut output);
    push_decl::<RenderList>(&mut output);
    output.truncate(output.trim_end().len());
    output.push('\n');
    output
}

pub fn runtime_contract_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../contracts/generated/runtime-dtos.ts")
}

pub fn write_runtime_contract(path: &Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, render_runtime_contract())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_has_provenance_and_all_boundary_types() {
        let output = render_runtime_contract();

        assert!(output.starts_with(GENERATED_HEADER));
        for type_name in [
            "WmlLoadDiagnostic",
            "ScriptExecutionOutcome",
            "ScriptInvocationOutcome",
            "ScriptDialogRequest",
            "ScriptTimerRequest",
            "EngineTraceEntry",
            "EngineDebugEvent",
            "EngineDebugSnapshot",
            "EngineDebugOpenSessionOutcome",
            "EnginePresentationFrame",
            "EngineInputEvent",
            "DrawCmd",
            "RenderList",
        ] {
            assert!(
                output.contains(&format!("export type {type_name} =")),
                "missing generated declaration for {type_name}"
            );
        }
        assert!(output.contains("navigationIntent: ScriptNavigationIntent"));
        assert!(output.contains("requiresRefresh: boolean"));
        assert!(output.contains("export interface EngineDebugConnector"));
        assert!(output.contains("export const ENGINE_DEBUG_CONTRACT_BASELINE"));
        assert!(output.contains("export const ENGINE_VIEWPORT_RANGE"));
        assert!(output.contains("maxCols: 4294967295"));
        assert!(output.contains("openDebugSession(request: EngineDebugOpenSessionRequest)"));
        assert!(output.contains("supportsSensitiveUnmasking: boolean"));
        assert!(output.contains(r#"{ "state": "masked", reason: EngineDebugRedactionReason, }"#));
        assert!(!output.contains(r#""state": "masked", value:"#));
        assert!(!output.contains("effects:"));
    }

    #[test]
    fn generated_contract_write_is_deterministic() {
        let path = std::env::temp_dir().join(format!(
            "wavenav-runtime-dtos-{}-{}.ts",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));

        write_runtime_contract(&path).expect("first generation should succeed");
        let first = fs::read(&path).expect("first output should be readable");
        write_runtime_contract(&path).expect("second generation should succeed");
        let second = fs::read(&path).expect("second output should be readable");

        assert_eq!(first, second);
        let _ = fs::remove_file(path);
    }
}
