// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: node ./scripts/generate-contract-wrappers.mjs

export { APPLICATION_STATE_ALLOWED_NETWORK_SCHEMES, APPLICATION_STATE_SAFE_KEYS, APPLICATION_STATE_SCHEMA_VERSION, APPLICATION_STATE_SENSITIVE_QUERY_KEYS, DEFAULT_APPLICATION_STATE_V1, MAX_SAFE_SESSION_EXAMPLE_ID_BYTES, MAX_SAFE_SESSION_FRAGMENT_BYTES, MAX_SAFE_SESSION_URL_BYTES } from "./generated/application-state-host";
export type { ApplicationSettingsV1, ApplicationStateComponent, ApplicationStateLoadResult, ApplicationStateLoadStatus, ApplicationStateV1, ClearApplicationStateComponentRequest, DefaultRunModePreference, DiagnosticPreferencesV1, DiagnosticRouteOverrideV1, FavoritesStateV1, HostThemePreference, OnboardingStateV1, PersistedFavoriteTargetV1, PersistedFavoriteV1, SafeSessionStateV1, SafeSessionV1, SaveApplicationStateRequest, StartBehaviorPreference, WindowBoundsV1, WindowStateV1 } from "./generated/application-state-host";
