// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: node ./scripts/generate-contract-wrappers.mjs

export type { AdvanceTimeRequest, DrawCmd, EngineHostClient, EngineKey, EngineRuntimeSnapshot, ExternalNavigationCacheControlPolicySnapshot, ExternalNavigationPostContextSnapshot, ExternalNavigationRequestPolicySnapshot, HandleKeyRequest, LoadDeckContextRequest, LoadDeckRequest, MoveFocusedSelectEditRequest, NavigateToCardRequest, RenderList, ScriptDialogRequestSnapshot, ScriptTimerRequestSnapshot, SetFocusedInputEditDraftRequest, SetViewportColsRequest } from "./generated/engine-host";
export type WmlDeckInput = import("./generated/engine-host").LoadDeckContextRequest;
export type ScriptDialogRequest = import("./generated/engine-host").ScriptDialogRequestSnapshot;
export type ScriptTimerRequest = import("./generated/engine-host").ScriptTimerRequestSnapshot;
