// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: node browser/scripts/generate-contract-wrappers.mjs

export type {
  AdvanceTimeRequest,
  DrawCmd,
  EngineHostClient,
  EngineKey,
  EngineRuntimeSnapshot,
  HandleKeyRequest,
  LoadDeckContextRequest,
  LoadDeckRequest,
  NavigateToCardRequest,
  RenderList,
  ScriptDialogRequestSnapshot,
  ScriptTimerRequestSnapshot,
  SetViewportColsRequest,
} from './generated/engine-host';

export type WmlDeckInput = import('./generated/engine-host').LoadDeckContextRequest;
export type ScriptDialogRequest = import('./generated/engine-host').ScriptDialogRequestSnapshot;
export type ScriptTimerRequest = import('./generated/engine-host').ScriptTimerRequestSnapshot;
