// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: node ./scripts/generate-contract-wrappers.mjs

export { HOST_INGRESS_LIMITS } from "./generated/host";
export type { HostCommandError, HostCommandErrorCode, HostIngressLimits } from "./generated/host";
