/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch a WAP resource through gateway transport */
        post: operations["fetchResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FetchRequest: {
            /**
             * Format: uri
             * @description Absolute URL to fetch through the gateway.
             */
            url: string;
            /**
             * @default GET
             * @enum {string}
             */
            method: "GET";
            /** @description Optional outbound request headers. */
            headers?: {
                [key: string]: string;
            };
            /** @default 5000 */
            timeoutMs: number;
            /** @default 1 */
            retries: number;
        };
        FetchResponse: {
            /** @description True when transport and decode completed successfully. */
            ok: boolean;
            /** @description Upstream/gateway response code when available. */
            status: number;
            /** @description Final resolved URL after redirects. */
            finalUrl: string;
            /** @description Detected content type for response payload. */
            contentType: string;
            /** @description Decoded WML XML text. Present when ok=true. */
            wml?: string;
            raw?: components["schemas"]["RawPayload"];
            error?: components["schemas"]["ErrorInfo"];
            timingMs: components["schemas"]["TimingMs"];
            engineDeckInput?: components["schemas"]["EngineDeckInput"];
        };
        RawPayload: {
            /** @description Raw body payload encoded in base64. */
            bytesBase64: string;
            contentType: string;
        };
        TimingMs: {
            encode: number;
            udpRtt: number;
            decode: number;
        };
        ErrorInfo: {
            /** @enum {string} */
            code: "INVALID_REQUEST" | "GATEWAY_TIMEOUT" | "RETRIES_EXHAUSTED" | "UNSUPPORTED_CONTENT_TYPE" | "WBXML_DECODE_FAILED" | "PROTOCOL_ERROR" | "TRANSPORT_UNAVAILABLE" | "INTERNAL_ERROR";
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        EngineDeckInput: {
            /** @description Normalized WML XML text for WASM engine ingestion. */
            wmlXml: string;
            /** @description Final URL after redirect resolution. */
            baseUrl: string;
            /** @description Normalized media type from upstream response. */
            contentType: string;
            /** @description Optional raw payload bytes in base64 for debug/fidelity workflows. */
            rawBytesBase64?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fetchResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchRequest"];
            };
        };
        responses: {
            /** @description Fetch completed (success or logical failure) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
